
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.util.Map;
import java.util.Set;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cinfe
 */
public class UserInterface extends javax.swing.JFrame {

    private String path;

    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField18 = new javax.swing.JTextField();
        chooseDyrectory = new java.awt.Button();
        selectedFileLabel = new java.awt.Label();
        methodSelect = new java.awt.Choice();
        label1 = new java.awt.Label();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        ccResult = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        evaluateButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TestingTool");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(720, 270));
        setMinimumSize(new java.awt.Dimension(720, 270));
        setPreferredSize(new java.awt.Dimension(720, 270));
        getContentPane().setLayout(null);

        chooseDyrectory.setLabel("Explorar directorio");
        chooseDyrectory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseDyrectoryMouseClicked(evt);
            }
        });
        chooseDyrectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDyrectoryActionPerformed(evt);
            }
        });
        getContentPane().add(chooseDyrectory);
        chooseDyrectory.setBounds(20, 20, 115, 24);

        selectedFileLabel.setBackground(new java.awt.Color(203, 204, 207));
        selectedFileLabel.setText("[Ruta de archivo seleccionado]");
        getContentPane().add(selectedFileLabel);
        selectedFileLabel.setBounds(160, 20, 505, 24);
        getContentPane().add(methodSelect);
        methodSelect.setBounds(210, 50, 197, 20);

        label1.setBackground(new java.awt.Color(203, 204, 207));
        label1.setText("Selecione el método a evaluar:");
        getContentPane().add(label1);
        label1.setBounds(20, 50, 173, 20);

        jTextField13.setEditable(false);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(170, 140, 44, 20);

        jTextField14.setEditable(false);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(380, 110, 44, 20);

        jTextField15.setEditable(false);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(170, 200, 44, 20);

        jTextField16.setEditable(false);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(170, 170, 44, 20);

        jTextField17.setEditable(false);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(170, 110, 44, 20);

        jTextField19.setEditable(false);
        getContentPane().add(jTextField19);
        jTextField19.setBounds(380, 170, 44, 20);

        ccResult.setEditable(false);
        getContentPane().add(ccResult);
        ccResult.setBounds(380, 140, 44, 20);

        jTextField21.setEditable(false);
        getContentPane().add(jTextField21);
        jTextField21.setBounds(380, 200, 44, 20);

        jTextField22.setEditable(false);
        getContentPane().add(jTextField22);
        jTextField22.setBounds(620, 110, 44, 20);

        jTextField23.setEditable(false);
        getContentPane().add(jTextField23);
        jTextField23.setBounds(620, 140, 44, 20);

        jTextField24.setEditable(false);
        getContentPane().add(jTextField24);
        jTextField24.setBounds(620, 170, 44, 20);

        jLabel2.setText("Líneas comentadas:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 170, 120, 20);

        jLabel3.setText("Líneas totales:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 120, 20);

        jLabel4.setText("Líneas de código:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 120, 20);

        jLabel5.setText("Líneas en blanco:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 200, 120, 20);

        jLabel6.setText("% comentarios:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 110, 118, 20);

        jLabel7.setText("Comp. Clicomática:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 140, 118, 20);

        jLabel8.setText("Fan in:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 170, 118, 20);

        jLabel9.setText("Fan out:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 200, 118, 20);

        jLabel10.setText("Halstead - Velocidad: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 140, 118, 20);

        jLabel11.setText("Líneas - Esfuerzo:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 170, 118, 20);

        jLabel13.setText("Halstead - Longitud: ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 110, 118, 20);

        evaluateButton.setEnabled(false);
        evaluateButton.setLabel("Evaluar método");
        evaluateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluateButtonMouseClicked(evt);
            }
        });
        getContentPane().add(evaluateButton);
        evaluateButton.setBounds(420, 50, 102, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(720, 270));
        jLabel1.setMinimumSize(new java.awt.Dimension(720, 270));
        jLabel1.setPreferredSize(new java.awt.Dimension(720, 270));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 710, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseDyrectoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseDyrectoryMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result;
        result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();

            this.path = path;

            selectedFileLabel.setText(path);
            try {
                ArrayList<String> methodsNames = Gestor.getMethodsNames(path);
                for (String methodName : methodsNames) {
                    methodSelect.addItem(methodName);
                }
                evaluateButton.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_chooseDyrectoryMouseClicked

    @Override
    public Image getIconImage() {
        Image retValue;
        retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("icon.png"));

        return retValue;
    }


    private void chooseDyrectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDyrectoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseDyrectoryActionPerformed

    private void evaluateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluateButtonMouseClicked
        try {
            //---CLEAN ALL --------
            ccResult.setText("");

            Map results = Gestor.getResults(this.path, methodSelect.getSelectedItem());
            ccResult.setText(results.get("cc").toString());

        } catch (IOException ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_evaluateButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccResult;
    private java.awt.Button chooseDyrectory;
    private java.awt.Button evaluateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private java.awt.Label label1;
    private java.awt.Choice methodSelect;
    private java.awt.Label selectedFileLabel;
    // End of variables declaration//GEN-END:variables

}
